version: '3.1'

services:
  wordle-db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - 4500:5432

  wordle-adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
