version: '3.1'

services:
  wordle-bot:
    build: .
    environment:
      - WORDLE_DB_USER=postgres
      - WORDLE_DB_PASSWORD=admin
      - WORDLE_DB_HOST=wordle-db
      - WORDLE_DB_PORT=5432
      - WORDLE_DB_NAME=postgres
      - WORDLE_DISCORD_BOT_APP_ID=<insert_your_bot_app_id_here>
      - WORDLE_DISCORD_BOT_TOKEN=<insert_your_bot_token_here>
      - WORDLE_ENVIRONMENT=dev
    depends_on:
      - wordle-db
  wordle-adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
    depends_on:
      - wordle-db
  wordle-db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - 4500:5432


